### ISSUE TITLE
regression: can no longer assign result of operators whose name matches a procedure

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#189]
Presumably as a consequence of #120 , the following is now rejected:
```
require import DBool.

type encseed, plaintext, ciphertext.
op dencseed : encseed distr.
op enc : encseed -> plaintext -> ciphertext.

module M = {  
  proc enc(m: plaintext) = {
    var es, c;
    es <$ dencseed;
    c <- enc es m;
    return c;
  } 

  proc chall (m0 m1 : plaintext) = {
    var es, c, b;
    b <$ {0,1};
    es <$ dencseed;
    c <- enc es (b?m0:m1);
    return c;
  } 
}.
```
The message is: "`enc` is a procedure name. Assign its result to a variable using `<@` instead"

IMHO, this should be accepted as the RHS of `<-` cannot contain any procedure calls. So there shouldn't be a any ambiguity here. 

CC: @fdupress

**Comment by fdupress** [comment]
Thanks. It's weird that none of the "standard" examples exercise this. I'll take a look, but it does look like it should be fixable without diving beyond typing.

**Comment by fdupress** [comment]
So... Interestingly, this was broken before #120 when the operator was applied to a single tuple-typed argument. I can easily recover that behaviour.

Any more advanced fix requires a bit of discussion regarding how we resolve cases where a procedure and operator share a name in general. Note that types are not used for operator selection, so I'd argue we shouldn't try to use them for disambiguation here either—but we need to decide if operators are selected over procedures or the other way around (the current situation).

@strub Thoughts on this?

**Comment by chdoc** [comment]
I'm not sure I understand. What's a context where both a procedure and an operator are syntactically legal in the same place? IIUC, For `<@` the right hand side must begin with a procedure (the one being called) and its argument must be a (tuple-typed) expression. For `<-` the RHS must be an expression, so it cannot involve a procedure.

**Comment by bgregoir** [comment]
I am also agree with Christian, if we have <@ and <-, and that proc call can only be <@ (which was not the case before), then <- should only look for operator.

**Comment by fdupress** [comment]
Indeed, that was me not thinking beyond "this should fail".

Error handling is going to suck.

**Comment by fdupress** [comment]
#192 removes the error message entirely—the easiest way to avoid checking if a procedure with that name exists.

I now have some exception handling going on in my local worktree, and wondering what people would prefer.
At the moment, I try to type the right-hand side as an expression; if it fails with an "Unknown operator" error where the operator name coincides with the name of an existing procedure, then I replace the "unknown operator" error with a "this is a procedure, use `<@`" error.

I am considering whether it might not be better to:
- stack the errors ("I can't find this op; by the way, if you meant to call the procedure, here is how you do it."); and
- stack the errors without even checking the condition that the underlying failure is due to an unknown operator whose name coincides with that of a procedure ("I can't type this as an expression; by the way, if you meant to call the procedure, here is how you do it.").

Of course, we could also decide to just remove the error message and assume that anybody who's been using `r2022.04` has been trained out of using `<-` for procedure calls.

**Comment by chdoc** [comment]
Something like "Cannot type ... as an expression, if you meant to call a procedure, assign its result using `<@` rather than `<-`".
