### ISSUE TITLE
conseq no longer checks procedure initialization restriction

### ISSUE THREAD

**Issue by alleystoughton** [EasyCrypt/easycrypt#206]
The following example shows that `conseq` (and presumably `apply`) no longer checks that procedures of module arguments respect the procedure initialization restriction (`proc *`).

```
require import AllCore Real Distr.

module type T = {
  proc *init() : bool
}.

module M(N : T) = {
  proc f() : bool = {
    var y : bool;
    y <@ N.init();
    return y;
  }
}.

(* this is fine: *)

lemma foo (N <: T) :
  equiv [M(N).f ~ M(N).f : true ==> ={res}].
proof.
proc.
call (_ : true).
auto.
qed.

module N : T = {
  var x : bool
  proc init() : bool = {  (* does not initialize x *)
    return x;
  }
}.

(* but this is not:  *)

lemma goo &m &n :
  N.x{m} => ! N.x{n} =>
  Pr[M(N).f() @ &m : res] = Pr[M(N).f() @ &n : res].
proof.
move => true_m false_n.
byequiv => //.
(* this shouldn't work, as N.init does not initialize N.x *)
by conseq (foo N).
qed.

(* if N really did initialize N.x, this wouldn't be provable: *)

lemma who &m &n :
  N.x{m} => ! N.x{n} =>
  Pr[M(N).f() @ &m : res] <> Pr[M(N).f() @ &n : res].
proof.
move => true_m false_n.
have -> : Pr[M(N).f() @ &m : res] = 1%r.
  byphoare (_ : N.x = N.x{m} ==> res) => //.
  proc; inline*; auto.
have -> : Pr[M(N).f() @ &n : res] = 0%r.
  byphoare (_ : N.x = N.x{n} ==> res) => //.
  hoare; proc; inline*; auto.
trivial.
qed.

(* not sure how to turn this into an unconditional proof of false *)

lemma bad &m &n :
  N.x{m} => ! N.x{n} => false.
proof.
move => true_m false_n.
have A := goo &m &n true_m false_n.
have B := who &m &n true_m false_n.
by rewrite A in B.
qed.
```

**Comment by fdupress** [comment]
Thanks, Alley.

In order to avoid having weird specialised mechanism, and now that we understand a bit more how abstract modules (and `proc *`) should and shouldn't be used in proofs, perhaps it's worth taking this opportunity to generalise this into a proper mechanism for specifying oracle properties.

I'd suggest:
- 3 new hint databases for properties of procedures for HL properties (partial correctness, data invariants), pHL properties (losslessness, probabilistic functional correctness) and pRHL properties (self-equivalence, including self-initialisation, read-only, statelessness, ...); eventually, these could also be used by `auto` but this might be confusing if done by default.
- An oracle tagging mechanism to automatically generate and add standard properties to the hint database.

In this case, the `*` annotation would become an annotation which generates an assumption (in `declare` or `exists`) or a proof obligation (in `forall` or `apply`) of the form `equiv [p ~ p: ={arg} ==> ={res, glob p}]`.

My hope is that relying on a more flexible mechanism that is more likely to be used (the `*` is too restrictive in practice), combined with making the checks an explicit proof obligation, will make it less likely we accidentally remove it without noticing.

**Comment by chdoc** [comment]
My impression is that this would require some careful thinking and design. Given that this is a soundness issue, I think this should be fixed ASAP, possibly considering generalizations at some later point.

**Comment by fdupress** [comment]
Yes, so for the avoidance of doubt, the quick fix I'm suggesting is to rip out `proc *`, say "good bye" and toss it into the fires of Mount Doom.

Its behaviour can be recovered more flexibly in other ways, for example by placing the relevant assumption (and discharging it where necessary) on the procedure instead of having it hidden away in the module type. (This means, in particular, that things we proved about an abstract starred procedure that don't actually need it to be starred can be used a lot more flexibly.)
A few `call (: true)` then need to be turned into `call its_a_proc_star`, where `its_a_proc_star` is the name of the assumption, and only where the fact that the procedure was an initialiser is actually used.

**Comment by chdoc** [comment]
> Yes, so for the avoidance of doubt, the quick fix I'm suggesting is to rip out `proc *`, say "good bye" and toss it into the fires of Mount Doom.

I'm perfectly fine with this. (Generally, I'm in favor of not adding things to the type system that can be achieved easily by conventional means.)

**Comment by alleystoughton** [comment]
I'd very very unhappy with just removing `proc *`. In particular, my ITP paper which is about to be published is too late to patch, and uses this feature.

Isn't this bug a regression, perhaps introduced during the cost model extensions?

**Comment by alleystoughton** [comment]
The following doesn't show an explicit unsoundness, but I would have thought these uses of `apply` should fail, depending upon the intended semantics of `proc *`.

```
module type T = {
  proc *f() : unit
}.

pred P.

axiom A (M <: T) : P.

module M : T = {
  var x : int

  proc f() : unit = {
  }
}.

print glob M.

(*
Globals [# = 0]:

Prog. variables [# = 1]:
  M.x : int
*)

lemma lem1 : P.
proof.
apply (A M).
qed.

module L = {
  var y : int

  proc g() : unit = {
    var z : int <- y;
  }
}.

module P : T = {
  proc f() : unit = {
    L.g();
  }
}.

print glob P.

(*
Globals [# = 0]:

Prog. variables [# = 1]:
  L.y : int
*)

lemma lem2 : P.
proof.
apply (A P).
qed.
```

**Comment by fdupress** [comment]
So in my first attempt at 175b1a9, I'd fixed the `*` flag to the wrong default. The error message "<Module> should initialize <variable>" showed up once(!) in the following run of `make check`, so the check is still implemented and triggered in some cases. This was in a `call`, whose parameter was a constructed proof term.

The function that emits this error message is `check_module_in`, from `ecPv.ml`. It is used in two places that appear to do extremely similar things:
- In `check_pterm_oarg` (line 816, `ecProofTerm.ml`); and
- In `check` (line 171, `ecLowGoal.ml`).

I still think we want to remove this, and ultimately replace it with a more generic constraint mechanism (which could also live more happily with the existing mechanism for cost constraints). But anyone who really wants to maintain a branch with `proc *` in it can probably use the information in this message to start reimplementing the checks.
