### ISSUE TITLE
unsoundness with probabilistic while 

### ISSUE THREAD

**Issue by chdoc** [EasyCrypt/easycrypt#212]
Turns out, the `while <invariant> <measure> <upper bound> <probability of decrease>` rule is unsound as well:

(the extra-logical `w : statement` made me very suspicious)

```
require import AllCore Distr.
type r_t, c_t.
op[lossless] dC : c_t distr. 
op p : c_t -> bool.

axiom mu_p : 0%r < mu dC p.

module M = { 
  proc p() = { 
    var c;
    var e <- true; 
    while (e) { 
      c <$ dC;
      if (p c) e <- false;
    } 
  }
}.

lemma good &m : Pr [ M.p() @ &m : true ] = 1%r.
proof.
byphoare => //; proc; sp. 
while true (b2i e) 1 (mu dC p) => //; 1:smt().
- move => ih; seq 2 : true 1%r 1%r 0%r _ => //.
  auto => />; smt(dC_ll).
- auto => />; smt(dC_ll).
- by rewrite mu_p /= => z; wp; rnd p; auto => />.   
qed.

lemma bad &m : Pr [ M.p() @ &m : true ] = 0%r.
proof.
byphoare => //; proc; sp. 
while true (b2i e) 1 (mu dC p) => //; 1:smt().
- move => ih. 
  seq 2 : true 1%r 0%r 0%r _ => //. 
- auto => />; smt(dC_ll).
- by rewrite mu_p /= => z; wp; rnd p; auto => />.   
qed.

lemma ugly &m : false.
proof.
suff : 0%r = 1%r by done. 
by rewrite -(good &m) -(bad &m).
qed.

```

**Comment by fdupress** [comment]
Yeah.

In the inductive step, we assume something about the behaviour of the loop *wrapped in a conditional*. For example, in your `bad` lemma, we get the following first goal:

```
&m: {}
w: statement
ih: phoare[ if (e) {...} : true ==> true] = 0%r
------------------------------------------------------------------------------------------------------------------
Context : {e : bool, c : c_t}
Bound   : [=] 0%r

pre = true /\ e

(1--)  c <$ dC                  
(2--)  if (p c) {               
(2.1)    e <- false             
(2--)  }                        
(3--)  if (e) {                 
(3.1)    w                      
(3--)  }                        

post = true
```

The assumption `ih` here, is obviously false (when `e` is initially `false`, it terminates trivially, regardless of the loop's behaviour). The assumption `ih` should be on `w` only (the loop itself).

I *think* this is enough to fix it, but I'd like to see the original pHL rule this is implementing (or to take the time to write a proof for this).

**Comment by chdoc** [comment]
I wasn't even aware that there is an (abstract) type `statement` that can be exposed to the user and used in statement judgments generated by tactics. I suppose since `statement` is not actually a type in the global context, there is no term of this type either. Are there any other tactics that introduce the `statement` type?

**Comment by fdupress** [comment]
I'm not aware of any others that use the `statement` meta-type, but there are a couple that create goals that can't be expressed in the user-facing syntax. (Judgments on statements, mostly.)

In this case, the `w : statement` is meant as a self-reference to the program (`c <$ dC; if (p c) { e <- false; } if (e) { w }`) itself, but we then botch the induction hypothesis, expressing it on a derived program, and possibly forgetting a precondition.

I'll be taking a stab at writing and sketching a proof for the rule in the next couple of days. @strub is also hoping that that will let us find a tactic that implements it without exposing the extra-logical self-reference. For example, we could build the `seq ...; if ...` into the tactic at virtually no cost, since the probability split and the proofs for the suffix are necessarily trivial.

**Comment by chdoc** [comment]
> For example, we could build the `seq ...; if ...` into the tactic at virtually no cost, since the probability split and the proofs for the suffix are necessarily trivial.

That was my thought as well. If `w` is abstract and the only thing one knows is the hypothesis generated by the tactic...

**Comment by strub** [comment]
One fix is to implement @fdupress's proposal: the induction hypothesis should be on `w` only. I am going to implement this fix first, but this does not preclude coming with a better while rules in the future.

**Comment by fdupress** [comment]
After another call with @bgregoir , where I finally understood the Universe, I've just pushed a further simplified `while` rule for pHL, which aligns (as far as I understand!) with the 2014 draft and its proof.

The general proof pattern is a bit heavier, but remains generally understandable: some of the conditional reasoning takes place in the bound itself, instead of happening solely in code.

PR coming up Soon™.

**Comment by strub** [comment]
@fdupress Where are we standing? Is your commit ready for a PR?

**Comment by fdupress** [comment]
The PR is still there, with Benjamin's commit on top, and verification that it implements the rules.

It could be improved for usability, but it's ready to merge for soundness.

**Comment by strub** [comment]
Oh, there is already a PR 😅
