### ISSUE TITLE
could conditional simplification hints discharge their assumptions from the goal's hypotheses?

### ISSUE THREAD

**Issue by alleystoughton** [EasyCrypt/easycrypt#444]
Consider the simplification hint:

```
require import AllCore List.

op q : int -> bool.
op p : int -> bool.

axiom f_ax (x : int) :
  q x => p x.

hint simplify [eqtrue] f_ax.
```

I expected it would be successfully applied in:

```
lemma foo :
  q 0 => p 0.
proof.
move => q_0.
simplify.
(*
x: int
q_0: q 0
------------------------------------------------------------------------
p 0
*)
abort.
```

But it seems that although `p 0` matches the conclusion of `f_ax`, generating a subgoal `q 0`, even though `q 0` is literally in the hypotheses of the goal, it isn't discharged, and so the conditional rule doesn't fire.

In contrast, see the following, where q 0 is introduced as its own simplification hint:

```
axiom q_0 :
  q 0.

hint simplify [eqtrue] q_0.

lemma foo' :
  p 0.
proof.
simplify.
(*
Type variables: <none>

------------------------------------------------------------------------
true
*)
trivial.
qed.
```

**Comment by bgregoir** [comment]
Simplification does not work like that, we try to match the conclusion of the rewriting in the current goal, here "p x".
If the rewrite rule has hypothesis, we then try to prove it using computation only, ie the hyp should be convertible with true.
If we try to do what you propose, we should be very careful: we need to take into account the contra-variance. 
I think this is what is done/allowed by setoid rewrite in Coq, but it is really a rewrite tactic and not a simplification.

**Comment by bgregoir** [comment]
Maybe it is because I do not really understand what you want to do.
if you want to replace occurence of q x by p x, this will trivially lead to issue.
 Assume, q x = false and p x = true.
    If the goal is q x and /= replaces it by p x it is trivially inconsistant. 
 We can do this replacement, if q x is in contra-variant position. 

 Remark that the current reduction does not try to replace q x by p x but really p x by true.
 To do that it find instance of p x and check if q x reduce to true. I think doing more (i.e try to prove q x using the context)
  is completely out of scope of current the reduction.

**Comment by alleystoughton** [comment]
OK, that makes sense. I'm trying to avoid using hint rewrite in some circumstances, because it's convenient not to have to explicitly invoke the rewriting hints database(s). But it's only an inconvenience.

**Comment by alleystoughton** [comment]
Closing this as not feasible.
