### ISSUE TITLE
First example of the reference manual

### ISSUE THREAD

**Issue by czhang-fm** [EasyCrypt/easycrypt#462]
Hi, I'm a newbie in EasyCrypt. When trying the first example on page 5-6 of the reference manual (https://cs-people.bu.edu/gaboardi/teaching/22-chalmers-course/easycrypt-refman.pdf), for the first lemma (i.e., x <$ {0,1} is equivalent to x xor y, with both x <$ {0,1} and y<$ {0,1}. )

lemma G1_G2_f : equiv[G1.f ~ G2.f : true ==> ={res}].
proof.
  proc.
  (* handle choice of x in G2.f *)
  seq 0 1 : true.
  rnd {2}. skip. smt.
  (* handle choice of x in G1.f / y in G2.f *)
  rnd (fun (z : bool) => z ^^ x{2}). skip. smt.
qed.

The second smt didn't get through in the proof_general. I think there might be something wrong with the weakest precondition tactics rnd (fun (z : bool) => z ^^ x{2}) but I don't know how to fix that. Any suggestion will be greatly appreciated. 

Thanks!

**Comment by czhang-fm** [comment]
BTW, is there any good tutorial for proving pRHL formulas?

**Comment by MM45** [comment]
Hi czhang,

First and foremost, for these kind of questions (i.e., questions about how things work in EC), it is preferred you first try the "EasyCrypt: questions & features" stream on the Formosa Zulip (see: https://formosa-crypto.zulipchat.com/).

Then, for your specific question, I would guess this problem mainly arises due to your SMT setup from the usual recommended one; for me, the proof does go through without any issue.

To see that, rather than the goal not being provable, the issue is probably that (with your setup) the SMT solvers simply cannot solve the goal (in time), you can prove the goal yourself without using `smt`. In this case, this can, for example, be done as follows:
```
lemma G1_G2_f : equiv[G1.f ~ G2.f : true ==> ={res}].
proof.
proc.
(* handle choice of x in G2.f *)
seq 0 1 : true.
+ rnd {2}. 
  skip.
  trivial.
(* handle choice of x in G1.f / y in G2.f *)
rnd (fun (z : bool) => z ^^ x{2}). 
skip.
move=> _ &2.
simplify.
split.
+ move => y yin.
  rewrite xorA xorK xor_false.
  trivial.
move=> _ x xin.
rewrite xorA xorK xor_false.
simplify.
rewrite xorC xorA xorK xor_false. 
trivial. 
qed.
```
Or, with a shorter and more concise proof:
```
lemma G1_G2_f : equiv[G1.f ~ G2.f : true ==> ={res}].
proof.
proc.
rnd (fun (z : bool) => z ^^ x{2}); rnd{2}; skip => /> x _.
by split => [| _] *; 2: rewrite {2}xorC /=; rewrite xorA xorK xor_false.
qed.
```
Hope this helps. Please join the aforementioned Zulip chat if you would like more assistance with these kinds of issues.
