### ISSUE TITLE
Case where SMT is very slow

### ISSUE THREAD

**Issue by mikeazo** [EasyCrypt/easycrypt#466]
I've put together a simplified version of something that I'm running into. I'm using the [EasyUC](https://github.com/easyuc/EasyUC) project, in particular the [EasyCrypt definitions](https://github.com/easyuc/EasyUC/tree/master/common).

I have a datatype with a large number of constructors (see SomeType.ec attached) and want to prove some statement (see TheProblem.ec).

If I bind MY_TYPE in SomeType.ec then SMT chokes unless I set the timeout high enough. If I remove the type binding, then SMT is very fast.

Is there an explanation for why this is happening or even better a way to fix it?

[SomeType.zip](https://github.com/EasyCrypt/easycrypt/files/13312331/SomeType.zip)

**Comment by alleystoughton** [comment]
I'll make this a self-contained example.

**Comment by alleystoughton** [comment]
Here is the self-contained version. The file `SomeType.ec` is in the Zip archive sent by Mike.

```
require import SomeType.  (* defines datatype MY_TYE with large
                             number of constructors *)

type t.
op f : t -> t -> bool.
op g : t -> t -> bool.

axiom f_g (x y : t) :
  f x y => g x y.

lemma foo (func : t, adv : t, varType : MY_TYPE) :
  f func adv => g func adv.
proof.
move => H.
(* this fails
prover timeout=3.
smt.
*)
prover timeout=5.
smt.
(* but if we take the binding of varType out, smt solves it
   in an instant - so the problem seems to be that the goal
   sent to why3 is very complex due to MY_TYPE having a very
   large number of constructors *)
```

Mike's question is whether it's possible to work using smt with datatypes (in this case an enumerated type) with very large numbers of constructors (in the example, about 680).

**Comment by fdupress** [comment]
The encoding of ADTs into SMT-LIB would certainly explain a slow-down, since each constructor is encoded as an uninterpreted function symbol, and injectivity and disjointness constraints are then added on as axioms. (If we're lucky, disjointness is done with a linear number of extra axioms, rather than the naive quadratic.) This is made worse if you use match expressions in any operators.

Even if everything SMT solvers do was simply linear in the number of declared symbols and axioms, this would very quickly blow up in your face. And SMT solvers most often do things that are superlinear, which means they blow up in your face faster.

You could try using `smt()` instead of `smt` to see if our pruning (which selects a small subset of symbols to encode to SMT when `smt(...)` is used) is clever enough to realise the symbols defining MY_TYPE are useless.

But I suspect pruning will not prune type and operator definitions, and you could look into changing that if you want—the SMT encoding itself is not in our control, but axiom selection is.

**Comment by alleystoughton** [comment]
In this case `smt(f_g).` is just as slow.

**Comment by strub** [comment]
We do not have any control on how datatypes are translated into smt solvers -- this is the role of Why3. And even there, I suspect that Why3 is going to have different encodings depending on the solvers -- some solvers have a naive notion of induction datatypes (notions that is going to be included in SMTLIB3 if I read well).

Anyway, the system is not designed for this. The only thing that we can offer is to add an option to make types opaque to smt solvers.

**Comment by strub** [comment]
Closing this issue this I got no feedback from the reporter.
